services:
  web:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    ports:
      - "${DEV_PORT}:3000"
    expose:
      - "3000"
    networks:
      - front-network

networks:
  front-network:
    name: erp-network
    external: true