services:
  web:
    build:
      context: .
      target: dev
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: package.json
        - action: rebuild
          path: next.config.ts
        - action: rebuild
          path: tsconfig.json
    environment:
      - WATCHPACK_POLLING=true
    env_file:
      - .env
    ports:
      - "${DEV_PORT}:3000"
    expose:
      - "3000"
    networks:
      - front-network

networks:
  front-network:
    name: erp-network
    external: true
