import type { Metadata } from "next";
import { Roboto } from "next/font/google";
// @ts-expect-error aaaaa
import "../globals.scss";
import SidebarMenu from "@/components/sidebarMenu";
import { ToastContainer } from "react-toastify";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GCP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${roboto.variable}`}>
        <SidebarMenu />
        <ToastContainer
          stacked
          position="top-center"
          autoClose={3000}
          theme="light"
        />
        {children}
      </body>
    </html>
  );
}
