import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../globals.scss";
import SidebarMenu from "@/components/sidebarMenu";
import { ToastContainer } from "react-toastify";
import { LoadingProvider } from "@/providers/loading.provider";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GCP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${roboto.variable}`}>
        <LoadingProvider>
          <SidebarMenu />
          <ToastContainer
            stacked
            position="top-center"
            autoClose={3000}
            theme="light"
          />
          {children}
        </LoadingProvider>
      </body>
    </html>
  );
}
